/// <reference types="react" />
import { ComponentMeta, ComponentStory } from '@storybook/react';
import Field from './Field';
declare const _default: ComponentMeta<(props: import("./Field").FieldProperties) => JSX.Element>;
export default _default;
export declare const Text: ComponentStory<typeof Field>;
export declare const Textarea: ComponentStory<typeof Field>;
export declare const Select: ComponentStory<typeof Field>;
export declare const Currency: ComponentStory<typeof Field>;
export declare const Address: ComponentStory<typeof Field>;
export declare const Phone: ComponentStory<typeof Field>;
export declare const DateOfBirth: ComponentStory<typeof Field>;
export declare const Duration: ComponentStory<typeof Field>;
export declare const Image: ComponentStory<typeof Field>;
export declare const Editor: ComponentStory<typeof Field>;
export declare const Password: ComponentStory<typeof Field>;
export declare const Search: ComponentStory<typeof Field>;
export declare const Timezone: ComponentStory<typeof Field>;
export declare const Toggle: ComponentStory<typeof Field>;
export declare const ToggleButton: ComponentStory<typeof Field>;
